import { Client, Professional, ServiceItem, Appointment, MarketingCampaign, Transaction, DailyCashRegister, CommissionPayout } from './types';

export const INITIAL_PROFESSIONALS: Professional[] = [
  {
    id: 'prof-1',
    name: 'Camila Meirelles',
    role: 'Master Colorista & Visagista',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    colorBadge: 'bg-rose-100 text-rose-800 border-rose-200',
    specialties: ['Balayage', 'Loiras Globais', 'Cortes Visagistas'],
    commissionRate: 50,
    rating: 4.9,
    phone: '5511987654321',
  },
  {
    id: 'prof-2',
    name: 'Lucas Antunes',
    role: 'Hair Stylist & Terapeuta Capilar',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    colorBadge: 'bg-amber-100 text-amber-800 border-amber-200',
    specialties: ['Tratamentos Fusio-Dose', 'Corte em Camadas', 'Escova Modelada'],
    commissionRate: 45,
    rating: 4.8,
    phone: '5511976543210',
  },
  {
    id: 'prof-3',
    name: 'Bruna Sato',
    role: 'Nail Artist & Instrutora',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    colorBadge: 'bg-purple-100 text-purple-800 border-purple-200',
    specialties: ['Alongamento em Fibra', 'Nail Art Minimalista', 'Blindagem'],
    commissionRate: 55,
    rating: 5.0,
    phone: '5511965432109',
  },
  {
    id: 'prof-4',
    name: 'Mariana Duarte',
    role: 'Lash & Brow Designer',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    colorBadge: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    specialties: ['Lash Lifting', 'Brow Lamination', 'Micropigmentação Shadow'],
    commissionRate: 50,
    rating: 4.9,
    phone: '5511954321098',
  },
  {
    id: 'prof-5',
    name: 'Dra. Vanessa Lima',
    role: 'Podologista Clínica & Spa dos Pés',
    avatar: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=150&auto=format&fit=crop&q=80',
    colorBadge: 'bg-teal-100 text-teal-800 border-teal-200',
    specialties: ['Podologia Preventiva', 'Correção de Unha com Órtese', 'Tratamento de Calosidades'],
    commissionRate: 50,
    rating: 5.0,
    phone: '5511943210987',
  },
  {
    id: 'prof-6',
    name: 'Renata Albuquerque',
    role: 'Especialista em Depilação & Bem-Estar',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
    colorBadge: 'bg-lime-100 text-lime-800 border-lime-200',
    specialties: ['Depilação com Cera Vegetal Calmante', 'Design Facial com Linha', 'Depilação a Laser'],
    commissionRate: 45,
    rating: 4.8,
    phone: '5511932109876',
  },
];

export const INITIAL_SERVICES: ServiceItem[] = [
  {
    id: 'srv-1',
    name: 'Mechas Balayage Signature + Tonalização',
    category: 'Cabelo',
    durationMinutes: 210,
    price: 680,
    description: 'Técnica exclusiva de iluminação com proteção Plex e banho de brilho nutritivo.',
    popular: true,
  },
  {
    id: 'srv-2',
    name: 'Corte Visagista & Finalização Sensorial',
    category: 'Cabelo',
    durationMinutes: 60,
    price: 190,
    description: 'Diagnóstico de linhas faciais, lavagem aromaterápica e styling personalizado.',
    popular: true,
  },
  {
    id: 'srv-3',
    name: 'Terapia Capilar & Spa Detox do Couro',
    category: 'Cabelo',
    durationMinutes: 75,
    price: 260,
    description: 'Microcâmera capilar, esfoliação botânica e infusão vitamínica profunda.',
    popular: false,
  },
  {
    id: 'srv-4',
    name: 'Alongamento em Fibra de Vidro (Novo Conjunto)',
    category: 'Unha',
    durationMinutes: 120,
    price: 240,
    description: 'Estrutura ultrafina natural com cutilagem russa e esmaltação em gel durável.',
    popular: true,
  },
  {
    id: 'srv-5',
    name: 'Manicure e Pedicure Express Spa',
    category: 'Unha',
    durationMinutes: 60,
    price: 110,
    description: 'Higienização, esfoliação com sais marinhos e esmaltação hipoalergênica.',
    popular: false,
  },
  {
    id: 'srv-podo-1',
    name: 'Tratamento Podológico Completo Jack Spa',
    category: 'Podologia',
    durationMinutes: 60,
    price: 180,
    description: 'Remoção de hiperqueratose, tratamento de lâmina ungueal, fissuras e hidratação com óleos essenciais.',
    popular: true,
  },
  {
    id: 'srv-podo-2',
    name: 'Podologia Preventiva & Órtese Ungueal',
    category: 'Podologia',
    durationMinutes: 45,
    price: 140,
    description: 'Desbaste e alinhamento biomecânico para conforto dos pés e alívio de pontos de pressão.',
    popular: false,
  },
  {
    id: 'srv-dep-1',
    name: 'Depilação Completa com Cera Calmante & Camomila',
    category: 'Depilação',
    durationMinutes: 50,
    price: 150,
    description: 'Cera 100% hipoalergênica com extrato calmante de camomila e finalização com água termal.',
    popular: true,
  },
  {
    id: 'srv-dep-2',
    name: 'Depilação Facial Egípcia (Linha Orgânica)',
    category: 'Depilação',
    durationMinutes: 30,
    price: 80,
    description: 'Remoção suave e precisa de penugem facial com fio 100% algodão antibacteriano.',
    popular: false,
  },
  {
    id: 'srv-6',
    name: 'Lash Lifting Queratinizado + Tintura',
    category: 'Sobrancelhas',
    durationMinutes: 60,
    price: 180,
    description: 'Curvatura natural e realce dos fios com complexo reconstrutor de queratina.',
    popular: true,
  },
  {
    id: 'srv-7',
    name: 'Design de Sobrancelhas + Brow Lamination',
    category: 'Sobrancelhas',
    durationMinutes: 50,
    price: 160,
    description: 'Alinhamento dos fios naturais com fixação prolongada e hidratação profunda.',
    popular: false,
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-1',
    name: 'Isabela Fontenele',
    phone: '5511991234567',
    email: 'isabela.fontenele@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    birthday: '18/09',
    status: 'VIP',
    totalSpent: 4320,
    visitsCount: 11,
    lastVisitDate: '2026-08-28',
    nextAppointmentDate: '2026-09-14',
    tags: ['Loiras VIP', 'Café Cappuccino', 'Adora Pontualidade'],
    preferences: {
      drink: 'Cappuccino com canela e água com gás gelada',
      conversationStyle: 'Discreta, prefere relaxar ou ler no momento da lavagem',
      allergies: 'Alérgica a fragrâncias sintéticas de jasmim',
      scalpCondition: 'Sensível, usar protetor dérmico antes do pó descolorante',
      notes: 'Cliente executiva. Gosta que o secador não fique na temperatura máxima.',
    },
    technicalRecords: [
      {
        id: 'rec-1',
        date: '28/08/2026',
        service: 'Mechas Balayage Signature',
        professional: 'Camila Meirelles',
        formula: 'Pó Blond Studio 9 + Ox 20vol (1:1.5). Tonalização: Shades EQ 09P + 09V com Processing Solution por 18 min.',
        observations: 'Clareamento atingiu fundo 9 sem marcas. Cabelo hidratado com Kérastase Résistance.',
      },
      {
        id: 'rec-2',
        date: '10/07/2026',
        service: 'Terapia Capilar & Corte',
        professional: 'Lucas Antunes',
        formula: 'Ampola Fusio-Dose Cicavita + Booster Reconstruction.',
        observations: 'Pontas secas eliminadas com corte bordado suave.',
      },
    ],
  },
  {
    id: 'cli-2',
    name: 'Carolina Bittencourt',
    phone: '5511982345678',
    email: 'carol.bittencourt@outlook.com',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    birthday: '03/10',
    status: 'Recorrente',
    totalSpent: 1850,
    visitsCount: 6,
    lastVisitDate: '2026-09-02',
    nextAppointmentDate: '2026-09-14',
    tags: ['Unhas em Gel', 'Manutenção Quinzenal'],
    preferences: {
      drink: 'Chá verde com hortelã morno',
      conversationStyle: 'Amigável e comunicativa, adora novidades de tendências',
      allergies: 'Nenhuma alergia relatada',
      scalpCondition: 'Normal',
      notes: 'Prefere esmaltes nudes leitosos ou francesinha degradê (baby boomer).',
    },
    technicalRecords: [
      {
        id: 'rec-3',
        date: '02/09/2026',
        service: 'Alongamento em Fibra',
        professional: 'Bruna Sato',
        formula: 'Gel Builder Cover Nude + Top Coat Diamond sem goma.',
        observations: 'Cutícula bem fina. Feita cutilagem a seco russa sem sangramentos.',
      },
    ],
  },
  {
    id: 'cli-3',
    name: 'Juliana Vasconcelos',
    phone: '5511973456789',
    email: 'ju.vasconcelos@adv.com.br',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    birthday: '14/09', // Aniversariante de hoje!
    status: 'Em Risco',
    totalSpent: 2980,
    visitsCount: 7,
    lastVisitDate: '2026-07-15',
    tags: ['Aniversariante Hoje', 'Ausente > 60 dias', 'Ex-Frequente'],
    preferences: {
      drink: 'Espresso curto sem açúcar',
      conversationStyle: 'Focada em trabalho, costuma responder e-mails durante o serviço',
      allergies: 'Sensibilidade a esmaltes com tolueno e formaldeído',
      scalpCondition: 'Oleosidade moderada na raiz',
      notes: 'Não vem ao salão há 61 dias. Excelente momento para contato pelo aniversário!',
    },
    technicalRecords: [
      {
        id: 'rec-4',
        date: '15/07/2026',
        service: 'Mechas & Glossing',
        professional: 'Camila Meirelles',
        formula: 'Raiz esfumada com 6.0 (Diarichesse) + banho de brilho 8.31.',
        observations: 'Cliente comentou que faria viagem corporativa longa em agosto.',
      },
    ],
  },
  {
    id: 'cli-4',
    name: 'Dra. Patricia Medeiros',
    phone: '5511964567890',
    email: 'patricia.medeiros@clinicamed.com',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    birthday: '22/11',
    status: 'VIP',
    totalSpent: 5600,
    visitsCount: 14,
    lastVisitDate: '2026-09-08',
    nextAppointmentDate: '2026-09-14',
    tags: ['VIP Diamond', 'Lash Lifting', 'Estética Facial'],
    preferences: {
      drink: 'Água saborizada com limão siciliano e alecrim',
      conversationStyle: 'Gosta de silêncio na sala de estética, música relaxante baixa',
      allergies: 'Sensibilidade a colas de extensão comuns. Usar apenas linha hipoalergênica',
      scalpCondition: 'Normal',
      notes: 'Costuma fechar pacotes trimestrais antecipados.',
    },
    technicalRecords: [
      {
        id: 'rec-5',
        date: '08/09/2026',
        service: 'Lash Lifting Queratinizado',
        professional: 'Mariana Duarte',
        formula: 'Loção lifting Perming 1 (10min) + Neutralizante 2 (8min) + Sérum Botulínico.',
        observations: 'Curvatura M selecionada. Resultado impecável e sem desconforto ocular.',
      },
    ],
  },
  {
    id: 'cli-5',
    name: 'Larissa Alencar',
    phone: '5511955678901',
    email: 'larissa.alencar@design.io',
    avatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=150&auto=format&fit=crop&q=80',
    birthday: '29/01',
    status: 'Nova',
    totalSpent: 380,
    visitsCount: 1,
    lastVisitDate: '2026-09-10',
    tags: ['Nova Cliente', 'Indicação da Isabela'],
    preferences: {
      drink: 'Café com leite de aveia',
      conversationStyle: 'Aberta a sugestões e consultoria de imagem',
      allergies: 'Nenhuma conhecida',
      scalpCondition: 'Seco e com pontas duplas',
      notes: 'Veio indicada pela Isabela Fontenele. Quer recuperar o cabelo de química anterior.',
    },
    technicalRecords: [
      {
        id: 'rec-6',
        date: '10/09/2026',
        service: 'Corte & Spa Detox',
        professional: 'Lucas Antunes',
        formula: 'Tratamento Olaplex No. 1 e No. 2 + Máscara 4-in-1.',
        observations: 'Teste de mecha aprovado para futuras luzes suaves.',
      },
    ],
  },
  {
    id: 'cli-6',
    name: 'Fernanda Nogueira',
    phone: '5511946789012',
    email: 'fernanda.nogueira@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80',
    birthday: '05/04',
    status: 'Recorrente',
    totalSpent: 2150,
    visitsCount: 5,
    lastVisitDate: '2026-08-14',
    tags: ['Cronograma Capilar', 'Fiel a Lucas'],
    preferences: {
      drink: 'Água mineral sem gás',
      conversationStyle: 'Muito pontual, tem apenas 1h livre no almoço',
      allergies: 'Nenhuma',
      scalpCondition: 'Normal',
      notes: 'Sempre solicita secagem rápida a 4 mãos se possível.',
    },
    technicalRecords: [
      {
        id: 'rec-7',
        date: '14/08/2026',
        service: 'Corte Visagista & Finalização',
        professional: 'Lucas Antunes',
        formula: 'Finalizador Termoativo Elixir Ultime.',
        observations: 'Corte em camadas longas para conferir movimento e leveza.',
      },
    ],
  },
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-1',
    clientId: 'cli-1',
    clientName: 'Isabela Fontenele',
    clientPhone: '5511991234567',
    clientAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    serviceId: 'srv-1',
    serviceName: 'Mechas Balayage Signature + Tonalização',
    professionalId: 'prof-1',
    professionalName: 'Camila Meirelles',
    date: '2026-09-14',
    time: '09:30',
    durationMinutes: 210,
    price: 680,
    status: 'em_atendimento',
    paymentStatus: 'pendente',
    notes: 'Atenção especial ao couro cabeludo sensível (usar protetor dérmico).',
  },
  {
    id: 'apt-2',
    clientId: 'cli-2',
    clientName: 'Carolina Bittencourt',
    clientPhone: '5511982345678',
    clientAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    serviceId: 'srv-4',
    serviceName: 'Alongamento em Fibra de Vidro',
    professionalId: 'prof-3',
    professionalName: 'Bruna Sato',
    date: '2026-09-14',
    time: '11:00',
    durationMinutes: 120,
    price: 240,
    status: 'confirmado',
    paymentStatus: 'pendente',
    notes: 'Manutenção baby boomer.',
  },
  {
    id: 'apt-3',
    clientId: 'cli-4',
    clientName: 'Dra. Patricia Medeiros',
    clientPhone: '5511964567890',
    clientAvatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    serviceId: 'srv-6',
    serviceName: 'Lash Lifting Queratinizado + Tintura',
    professionalId: 'prof-4',
    professionalName: 'Mariana Duarte',
    date: '2026-09-14',
    time: '14:00',
    durationMinutes: 60,
    price: 180,
    status: 'confirmado',
    paymentStatus: 'pendente',
    notes: 'Sala de estética com aromatizador de lavanda e música baixa.',
  },
  {
    id: 'apt-4',
    clientId: 'cli-5',
    clientName: 'Larissa Alencar',
    clientPhone: '5511955678901',
    clientAvatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=150&auto=format&fit=crop&q=80',
    serviceId: 'srv-2',
    serviceName: 'Corte Visagista & Finalização Sensorial',
    professionalId: 'prof-2',
    professionalName: 'Lucas Antunes',
    date: '2026-09-14',
    time: '15:30',
    durationMinutes: 60,
    price: 190,
    status: 'agendado',
    paymentStatus: 'pendente',
    notes: 'Segunda sessão do plano de recuperação capilar.',
  },
  {
    id: 'apt-5',
    clientId: 'cli-6',
    clientName: 'Fernanda Nogueira',
    clientPhone: '5511946789012',
    clientAvatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80',
    serviceId: 'srv-3',
    serviceName: 'Terapia Capilar & Spa Detox',
    professionalId: 'prof-2',
    professionalName: 'Lucas Antunes',
    date: '2026-09-14',
    time: '17:00',
    durationMinutes: 75,
    price: 260,
    status: 'agendado',
    paymentStatus: 'pendente',
  },
];

export const MARKETING_CAMPAIGNS: MarketingCampaign[] = [
  {
    id: 'camp-1',
    title: 'Aniversariantes do Mês',
    category: 'Aniversário',
    targetAudience: 'Clientes completando ano em Setembro (ex: Juliana Vasconcelos)',
    estimatedReach: 4,
    suggestedAction: 'Cupom de 20% OFF em qualquer procedimento ou Spa Day de presente',
    templateMessage: 'Olá {NOME}! 🌿 A equipe do Instituto Jack deseja um feliz aniversário! Para celebrar o seu dia especial, preparamos um mimo exclusivo de 20% OFF no seu próximo procedimento ou uma hidratação sensorial de presente. Cuidado que transforma, beleza que realça! Quer agendar seu momento de autocuidado esta semana?',
  },
  {
    id: 'camp-2',
    title: 'Lembrete de Retoque de Mechas (45-60 dias)',
    category: 'Retoque',
    targetAudience: 'Clientes de Mechas & Balayage sem retorno há mais de 45 dias',
    estimatedReach: 7,
    suggestedAction: 'Convite para tonalização express & revitalização de brilho',
    templateMessage: 'Oi {NOME}, tudo bem? 🤍 Notamos que já faz quase 2 meses desde suas últimas mechas aqui no Instituto Jack. Que tal renovarmos o banho de brilho e neutralizar os tons com nossa equipe? Temos alguns horários especiais abertos para você esta semana!',
  },
  {
    id: 'camp-3',
    title: 'Resgate de Clientes Ausentes (> 45 dias)',
    category: 'Reativação',
    targetAudience: 'Clientes frequentes que não visitam o salão há mais de 45 dias',
    estimatedReach: 12,
    suggestedAction: 'Oferta de boas-vindas de volta + diagnóstico capilar gratuito com microcâmera',
    templateMessage: 'Sentimos sua falta por aqui, {NOME}! ✨ Como estão seus cuidados? Preparamos uma condição super carinhosa no Instituto Jack: agendando qualquer procedimento de Cabelo, Podologia ou Unhas esta semana, você ganha um mimo especial de boas-vindas.',
  },
  {
    id: 'camp-4',
    title: 'Pesquisa de Satisfação & NPS Pós-Atendimento',
    category: 'Pós-Venda',
    targetAudience: 'Clientes atendidas nas últimas 24 horas',
    estimatedReach: 5,
    suggestedAction: 'Feedback de experiência e recomendação no Google Maps',
    templateMessage: 'Olá {NOME}, esperamos que você esteja amando o resultado do seu atendimento de hoje! 🥰 Sua opinião é muito valiosa para nós. Como você avalia sua experiência de 0 a 10 no Instituto Jack hoje? Se quiser deixar uma avaliação no Google, ficaremos imensamente gratos!',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    description: 'Mechas Balayage Signature + Tonalização',
    type: 'receita',
    category: 'Serviços de Cabelo',
    amount: 680,
    date: '2026-09-14',
    dueDate: '2026-09-14',
    paymentMethod: 'pix',
    status: 'pago',
    clientOrSupplier: 'Helena Albuquerque',
    professionalId: 'prof-1',
    professionalName: 'Camila Meirelles',
    appointmentId: 'apt-1',
    notes: 'Pagamento instantâneo via QR Code Pix',
  },
  {
    id: 'tx-2',
    description: 'Kit Home Care Kérastase Nutritive (Shampoo + Máscara)',
    type: 'receita',
    category: 'Venda de Produtos (Home Care)',
    amount: 480,
    date: '2026-09-14',
    dueDate: '2026-09-14',
    paymentMethod: 'credito',
    status: 'pago',
    clientOrSupplier: 'Helena Albuquerque',
    professionalId: 'prof-1',
    professionalName: 'Camila Meirelles',
    notes: 'Venda casada pós-procedimento de mechas',
  },
  {
    id: 'tx-3',
    description: 'Alongamento em Fibra de Vidro + Esmaltação em Gel',
    type: 'receita',
    category: 'Unhas & Nail Art',
    amount: 320,
    date: '2026-09-14',
    dueDate: '2026-09-14',
    paymentMethod: 'credito',
    status: 'pago',
    clientOrSupplier: 'Juliana Vasconcelos',
    professionalId: 'prof-3',
    professionalName: 'Bruna Sato',
    appointmentId: 'apt-3',
  },
  {
    id: 'tx-4',
    description: 'Óleo Reparador Wella Oil Reflections 100ml',
    type: 'receita',
    category: 'Venda de Produtos (Home Care)',
    amount: 165,
    date: '2026-09-14',
    dueDate: '2026-09-14',
    paymentMethod: 'pix',
    status: 'pago',
    clientOrSupplier: 'Carolina Mendes',
    professionalId: 'prof-2',
    professionalName: 'Lucas Antunes',
  },
  {
    id: 'tx-5',
    description: 'Tratamento Fusio-Dose Kérastase + Escova Modelada',
    type: 'receita',
    category: 'Serviços de Cabelo',
    amount: 340,
    date: '2026-09-14',
    dueDate: '2026-09-14',
    paymentMethod: 'debito',
    status: 'pago',
    clientOrSupplier: 'Mariana Penteado',
    professionalId: 'prof-2',
    professionalName: 'Lucas Antunes',
    appointmentId: 'apt-5',
  },
  {
    id: 'tx-6',
    description: 'Aluguel do Imóvel & Condomínio Boutique (Set/2026)',
    type: 'despesa',
    category: 'Aluguel & Condomínio',
    amount: 4500,
    date: '2026-09-10',
    dueDate: '2026-09-10',
    paymentMethod: 'boleto',
    status: 'pago',
    clientOrSupplier: 'Imobiliária Jardins Corp',
    notes: 'Imóvel principal com IPTU incluso',
  },
  {
    id: 'tx-7',
    description: 'Reposição Linha Wella Blondor & Koleston Mechas',
    type: 'despesa',
    category: 'Produtos & Químicas (Estoque)',
    amount: 1850,
    date: '2026-09-12',
    dueDate: '2026-09-12',
    paymentMethod: 'pix',
    status: 'pago',
    clientOrSupplier: 'Distribuidora Bella Cosméticos',
  },
  {
    id: 'tx-8',
    description: 'Energia Elétrica Enel (Ar Condicionado + Lavatórios)',
    type: 'despesa',
    category: 'Água & Luz & Internet',
    amount: 980,
    date: '2026-09-15',
    dueDate: '2026-09-18',
    paymentMethod: 'boleto',
    status: 'pendente',
    clientOrSupplier: 'Enel Distribuição',
    notes: 'Vence em 4 dias',
  },
  {
    id: 'tx-9',
    description: 'Comissão Quinzenal - Camila Meirelles (Cabelo)',
    type: 'despesa',
    category: 'Comissões Profissionais',
    amount: 3150,
    date: '2026-09-05',
    dueDate: '2026-09-05',
    paymentMethod: 'pix',
    status: 'pago',
    clientOrSupplier: 'Camila Meirelles',
    professionalId: 'prof-1',
    professionalName: 'Camila Meirelles',
    notes: '1ª quinzena de Setembro liquidada',
  },
  {
    id: 'tx-10',
    description: 'Comissão Quinzenal - Bruna Sato (Nails)',
    type: 'despesa',
    category: 'Comissões Profissionais',
    amount: 1760,
    date: '2026-09-05',
    dueDate: '2026-09-05',
    paymentMethod: 'pix',
    status: 'pago',
    clientOrSupplier: 'Bruna Sato',
    professionalId: 'prof-3',
    professionalName: 'Bruna Sato',
  },
  {
    id: 'tx-11',
    description: 'Campanha Meta Ads (Instagram Feed & Stories Salon)',
    type: 'despesa',
    category: 'Marketing & Tráfego Pago',
    amount: 600,
    date: '2026-09-13',
    dueDate: '2026-09-13',
    paymentMethod: 'credito',
    status: 'pago',
    clientOrSupplier: 'Meta Platforms Inc',
  },
  {
    id: 'tx-12',
    description: 'Taxa Maquininha Stone / Antecipação de Cartões',
    type: 'despesa',
    category: 'Taxas Bancárias / Cartão',
    amount: 310,
    date: '2026-09-14',
    dueDate: '2026-09-14',
    paymentMethod: 'debito',
    status: 'pago',
    clientOrSupplier: 'Stone Pagamentos',
  },
  {
    id: 'tx-13',
    description: 'Manutenção Preventiva Lavatórios & Filtros Ozônio',
    type: 'despesa',
    category: 'Manutenção & Infraestrutura',
    amount: 420,
    date: '2026-09-20',
    dueDate: '2026-09-22',
    paymentMethod: 'pix',
    status: 'pendente',
    clientOrSupplier: 'HidroFix Salões',
  },
];

export const INITIAL_CASH_REGISTERS: DailyCashRegister[] = [
  {
    id: 'cr-today',
    date: '2026-09-14',
    openingBalance: 350,
    status: 'aberto',
    cashIn: 280,
    pixIn: 845,
    cardIn: 800,
    withdrawals: 50,
    openedAt: '08:45',
    notes: 'Fundo inicial de R$ 350 em notas trocadas para troco.',
  },
  {
    id: 'cr-yesterday',
    date: '2026-09-13',
    openingBalance: 350,
    status: 'fechado',
    cashIn: 420,
    pixIn: 1450,
    cardIn: 2100,
    withdrawals: 80,
    closingBalance: 690,
    openedAt: '08:50',
    closedAt: '20:10',
    notes: 'Fechamento perfeito sem divergência de caixa físico.',
  },
];

export const INITIAL_COMMISSIONS: CommissionPayout[] = [
  {
    id: 'com-1',
    professionalId: 'prof-1',
    professionalName: 'Camila Meirelles',
    professionalAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    period: '01/09 a 15/09/2026',
    totalServicesAmount: 7200,
    commissionRate: 50,
    grossCommission: 3600,
    productDeduction: 150,
    cardFeeDeduction: 90,
    netCommission: 3360,
    status: 'pendente',
  },
  {
    id: 'com-2',
    professionalId: 'prof-2',
    professionalName: 'Lucas Antunes',
    professionalAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    period: '01/09 a 15/09/2026',
    totalServicesAmount: 4800,
    commissionRate: 45,
    grossCommission: 2160,
    productDeduction: 80,
    cardFeeDeduction: 60,
    netCommission: 2020,
    status: 'pendente',
  },
  {
    id: 'com-3',
    professionalId: 'prof-3',
    professionalName: 'Bruna Sato',
    professionalAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    period: '01/09 a 15/09/2026',
    totalServicesAmount: 3900,
    commissionRate: 55,
    grossCommission: 2145,
    productDeduction: 0,
    cardFeeDeduction: 50,
    netCommission: 2095,
    status: 'pendente',
  },
  {
    id: 'com-4',
    professionalId: 'prof-4',
    professionalName: 'Mariana Duarte',
    professionalAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    period: '01/09 a 15/09/2026',
    totalServicesAmount: 2600,
    commissionRate: 50,
    grossCommission: 1300,
    productDeduction: 0,
    cardFeeDeduction: 35,
    netCommission: 1265,
    status: 'pago',
    paidAt: '2026-09-14 11:30',
  },
];

